# Generated by Django 3.2.16 on 2023-04-06 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=100)),
                ('pageid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('media', models.ImageField(blank=True, upload_to='my_pic')),
            ],
        ),
        migrations.CreateModel(
            name='pmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_category', models.CharField(max_length=100)),
                ('inv_count', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('prod_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projectbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('proj_category', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('proj_name', models.CharField(max_length=200)),
                ('proj_category', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
                ('review', models.TextField(max_length=100)),
                ('details', models.TextField()),
                ('project_type', models.CharField(max_length=100)),
                ('proj_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('member_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('inv_count', models.IntegerField()),
                ('c_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('is_suspend', models.BooleanField(default=False)),
                ('suspend_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('p_rating', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_url', models.CharField(max_length=100)),
                ('UserPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoadmin_apis.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('p_rating', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_url', models.CharField(max_length=100)),
                ('UserPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoadmin_apis.userdetails')),
            ],
        ),
    ]
