# Generated by Django 3.2.16 on 2023-04-15 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pagename', models.CharField(max_length=100)),
                ('pageid', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('media', models.ImageField(blank=True, upload_to='my_pic')),
            ],
        ),
        migrations.CreateModel(
            name='CRM',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usname', models.CharField(max_length=50, unique=True)),
                ('pic_url', models.URLField()),
                ('abt', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('net_purchase_amount', models.CharField(max_length=50)),
                ('net_purchase_count', models.IntegerField()),
                ('pts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usname', models.CharField(max_length=50, unique=True)),
                ('emai', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=50)),
                ('inv_count', models.IntegerField()),
                ('member_name', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('pic_url', models.URLField()),
                ('is_suspended', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='pmsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_category', models.CharField(max_length=100)),
                ('inv_count', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('prod_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pic_url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('proj_category', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=50)),
                ('inv_count', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('net_purchase_item_count', models.IntegerField()),
                ('featured_flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projectbooking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('proj_category', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManagementModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('proj_name', models.CharField(max_length=200)),
                ('proj_category', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
                ('review', models.TextField(max_length=100)),
                ('details', models.TextField()),
                ('project_type', models.CharField(max_length=100)),
                ('proj_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic_url', models.URLField()),
                ('prod_name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('amt', models.CharField(max_length=50)),
                ('reviewer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('registerar', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('support_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic_url', models.URLField()),
                ('prod_name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('amt', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('uid', models.IntegerField(unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('is_suspend', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('suspend_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('p_rating', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_url', models.CharField(max_length=100)),
                ('UserPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoadmin_apis.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='my_pic')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('p_rating', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_url', models.CharField(max_length=100)),
                ('UserPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoadmin_apis.userdetails')),
            ],
        ),
    ]
