# Generated by Django 3.2.16 on 2023-04-19 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsmodel',
            name='pageid',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
