# Generated by Django 3.2.16 on 2023-04-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_suspend',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
