# Generated by Django 3.2.16 on 2023-04-19 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0003_auto_20230419_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsmodel',
            name='pageid',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='config_setting',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pmsmodel',
            name='prod_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectbooking',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectmanagementmodel',
            name='proj_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchased_item',
            name='pid',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supportdetails',
            name='support_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='pid',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
