# Generated by Django 3.2.16 on 2023-04-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0004_auto_20230419_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagementmodel',
            name='review',
            field=models.IntegerField(),
        ),
    ]
