# Generated by Django 3.2.16 on 2023-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0005_alter_projectmanagementmodel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_setting',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
