# Generated by Django 3.2.16 on 2023-04-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0007_alter_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsmodel',
            name='title',
        ),
    ]
