# Generated by Django 3.2.16 on 2023-04-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0008_remove_cmsmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='status',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
