# Generated by Django 3.2.16 on 2023-04-21 20:46

from django.db import migrations, models
import renoadmin_apis.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0011_auto_20230422_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsmodel',
            name='media',
            field=models.ImageField(blank=True, upload_to=renoadmin_apis.models.cmsModel.nameFile),
        ),
        migrations.AlterField(
            model_name='crm',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pmsmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to=renoadmin_apis.models.pmsModel.nameFile),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectmanagementmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to=renoadmin_apis.models.ProjectManagementModel.nameFile),
        ),
        migrations.AlterField(
            model_name='purchased_item',
            name='pic',
            field=models.ImageField(blank=True, upload_to=renoadmin_apis.models.Purchased_item.nameFile),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supportdetails',
            name='pic',
            field=models.ImageField(blank=True, upload_to=renoadmin_apis.models.SupportDetails.nameFile),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='pic',
            field=models.ImageField(blank=True, upload_to=renoadmin_apis.models.User_Product.nameFile),
        ),
    ]
