# Generated by Django 3.2.16 on 2023-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0012_auto_20230422_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsmodel',
            name='project_details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pmsmodel',
            name='inv_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pmsmodel',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
    ]
