# Generated by Django 3.2.16 on 2023-04-22 20:21

from django.db import migrations, models
import renoadmin_apis.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0014_alter_projectmanagementmodel_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('pic_url', models.ImageField(blank=True, upload_to=renoadmin_apis.models.listings.nameFile)),
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('rate', models.IntegerField(blank=True)),
            ],
        ),
    ]
