# Generated by Django 3.2.16 on 2023-04-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0019_alter_projectmanagementmodel_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='featured_flag',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
