# Generated by Django 3.2.16 on 2023-05-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0022_auto_20230504_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config_setting',
            old_name='username',
            new_name='mail',
        ),
    ]
