# Generated by Django 3.2.16 on 2023-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0023_rename_username_config_setting_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_setting',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
