# Generated by Django 4.0.10 on 2023-05-07 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0024_alter_config_setting_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('usname', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=256)),
                ('role', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
