# Generated by Django 3.2.16 on 2023-05-08 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0025_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
