# Generated by Django 3.2.16 on 2023-05-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0026_alter_userdetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbooking',
            name='proj_category',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
