# Generated by Django 4.0.10 on 2023-05-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0028_auto_20230510_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm',
            name='email',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
