# Generated by Django 4.0.10 on 2023-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0030_reviews_rate_alter_products_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config_setting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='config_setting',
            name='mail',
        ),
        migrations.AddField(
            model_name='config_setting',
            name='admin_mail',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='config_setting',
            name='support_email',
            field=models.CharField(default='', max_length=64),
        ),
    ]
