# Generated by Django 4.0.10 on 2023-05-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0032_config_setting_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config_setting',
            old_name='username',
            new_name='usname',
        ),
    ]
