# Generated by Django 4.0.10 on 2023-05-27 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0033_rename_username_config_setting_usname'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpdeskTickets',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('usname', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=256)),
                ('status', models.CharField(max_length=20)),
                ('conversations', models.JSONField()),
            ],
        ),
    ]
