# Generated by Django 4.0.10 on 2023-06-10 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renoadmin_apis', '0034_helpdesktickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('prod_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('catg', models.CharField(max_length=200)),
                ('offer_by', models.CharField(max_length=20)),
                ('offer_val', models.FloatField()),
                ('expiry', models.CharField(max_length=20)),
            ],
        ),
    ]
